### ISSUE TITLE
Метод public int sumGenre(String genre) не суммирует время игр

### ISSUE THREAD

**Issue by VladislavChu** [Ziplay1997/TeamWork#2]
# Описание
Метод public int sumGenre(String genre) не суммирует время игр
# Локализация дефекта
https://github.com/Ziplay1997/TeamWork/blob/3124055be799bdba675efc3d37c5165d2d9ef059/src/main/java/ru/netology/Player.java#L45

org.opentest4j.AssertionFailedError:
Expected :3
Actual :0
# Шаги воспроизведения 
1. Открыть проект TeamWork в Intellij IDEA.
2. Запустить [тест](https://github.com/Ziplay1997/TeamWork/blob/main/src/test/java/ru/netology/PlayerTest.java#L8-L20)
# Скриншот
![bug1](https://user-images.githubusercontent.com/117576235/222140507-22591948-2b88-4e73-89bf-6539a96468e0.jpg)
# Окружение
Операционная система: Windows 11 Pro
IDE: IntelliJ IDEA Community Edition 2022.3
Java: OpenJDK 11.0.16.1

**Comment by Ziplay1997** [comment]
# Баг исправлен
![1](https://user-images.githubusercontent.com/59051762/222140100-ffdc6638-4cda-4269-96b2-2c323fd7b0bc.jpg)
