### ISSUE TITLE
Метод SumGenre не суммирует время нескольких игр в каталоге

### ISSUE THREAD

**Issue by VladislavChu** [Ziplay1997/TeamWork#3]
# Описание
Метод SumGenre не суммирует время игр при наличии нескольких игр в каталоге.
# Локализация дефекта
https://github.com/Ziplay1997/TeamWork/blob/3124055be799bdba675efc3d37c5165d2d9ef059/src/main/java/ru/netology/Player.java#L45-L55
# Шаги воспроизведения
1. Открыть [код программы](https://github.com/Ziplay1997/TeamWork/blob/main/src/main/java/ru/netology/Player.java#L45-L55) в IDEA
2. Запустить [тест](https://github.com/Ziplay1997/TeamWork/blob/main/src/test/java/ru/netology/PlayerTest.java#L24-L42)
3. Посмотреть на вывод результата в консоли
Ожидаемый результат: 3
Фактический результат: 0
# Скриншот
![bug2](https://user-images.githubusercontent.com/117576235/222140723-fc340206-c40e-48aa-8ab3-b06a04faf372.jpg)
# Окружение
Операционная система: Windows 11 Pro
IDE: IntelliJ IDEA Community Edition 2022.3
Java: OpenJDK 11.0.16.1

**Comment by Ziplay1997** [comment]
# Код исправлен 
![1](https://user-images.githubusercontent.com/59051762/222148549-2756fe63-2062-47de-87bd-58c067781439.jpg)
![2](https://user-images.githubusercontent.com/59051762/222148567-64d5e325-0e18-4e93-96dd-15e7cd18f3b0.jpg)
