### ISSUE TITLE
Метод public int play не выдает RunTimeExeption

### ISSUE THREAD

**Issue by VladislavChu** [Ziplay1997/TeamWork#4]
# Описание
Вызов к неустановленной игре не выдает RunTimeExeption в методе public int play(Game game, int hours)
# Локализация дефекта
https://github.com/Ziplay1997/TeamWork/blob/1b9867d0b536e21011179b3b5dd0a8a6401f5668/src/main/java/ru/netology/Player.java#L33-L41
# Шаги воспроизведения 
1. Открыть [код программы](https://github.com/Ziplay1997/TeamWork/blob/main/src/main/java/ru/netology/Player.java#L33-L41) в IDEA.
2. Запустить [тест](https://github.com/Ziplay1997/TeamWork/blob/main/src/test/java/ru/netology/PlayerTest.java#L45-L60).
3. Посмотреть на результат в консоли.
Ожидаемый результат: Выводится ошибка "RuntimeException"
Фактический результат: org.opentest4j.AssertionFailedError: Expected java.lang.RuntimeException to be thrown, but nothing was thrown.
# Скриншот
![bug3](https://user-images.githubusercontent.com/117576235/222140835-a8bcba2a-374c-4e3e-8f11-b67a2af62152.jpg)
# Окружение 
Операционная система: Windows 11 Pro
IDE: IntelliJ IDEA Community Edition 2022.3
Java: OpenJDK 11.0.16.1

**Comment by Ziplay1997** [comment]
# Код исправлен

![2](https://user-images.githubusercontent.com/59051762/222149843-a604a9f9-3554-438c-b7a7-a39d6190bd83.jpg)
