### ISSUE TITLE
Метод mostPlayerByGenre возвращает null при установленных играх

### ISSUE THREAD

**Issue by VladislavChu** [Ziplay1997/TeamWork#5]
# Описание
Метод mostPlayerByGenre(String genre) при наличии установленных игр всегда возвращает null. Не выдавая жанр игры
# Локализация дефекта
https://github.com/Ziplay1997/TeamWork/blob/49fb597aa50de6cb745a0ff17b7c7d38d5cccbb2/src/main/java/ru/netology/Player.java#L59-L61
# Шаги воспроизведения
1. Открыть [код программы](https://github.com/Ziplay1997/TeamWork/blob/main/src/main/java/ru/netology/Player.java#L59-L61)
2. Запустить [тест](https://github.com/Ziplay1997/TeamWork/blob/main/src/test/java/ru/netology/PlayerTest.java#L83-L101)
3. Посмотреть на результат теста в консоли.
Ожидаемый результат: Call of Duty
Фактический результат: null
# Скриншот
![bug4](https://user-images.githubusercontent.com/117576235/222140902-5f50903b-7e72-4b34-bd6c-c9da68cf798f.jpg)
# Окружение
Операционная система: Windows 11 Pro
IDE: IntelliJ IDEA Community Edition 2022.3
Java: OpenJDK 11.0.16.1

**Comment by Ziplay1997** [comment]
# Код исправлен
![3](https://user-images.githubusercontent.com/59051762/222151641-b42ec270-95eb-47db-bb9c-d6fa9033ae1d.jpg)
