### ISSUE TITLE
К коллекции playedTime нет доступа

### ISSUE THREAD

**Issue by VladislavChu** [Ziplay1997/TeamWork#6]
# Описание
Невозможно обратиться к коллекции playedTime в классе Player. 
# Локализация дефекта
https://github.com/Ziplay1997/TeamWork/blob/249d6adede18a3bfc1ce54e9ca98a817685c9407/src/main/java/ru/netology/Player.java#L12 
# Шаги воспроизведения
1. Открыть [код программы](https://github.com/Ziplay1997/TeamWork/blob/main/src/test/java/ru/netology/PlayerTest.java#L136-L148) в IDEA.
2. Запустить тест shouldInstallNewGame.
3. Посмотреть на вывод в консоли.
# Скриншот
![bug5](https://user-images.githubusercontent.com/117576235/222141059-88c45f67-3a2b-4bd5-96f6-e72337465d82.jpg)
# Окружение 
Операционная система: Windows 11 Pro
IDE: IntelliJ IDEA Community Edition 2022.3
Java: OpenJDK 11.0.16.1

**Comment by Ziplay1997** [comment]
# Код исправлен
Изменен модификатор доступа на protected
![4](https://user-images.githubusercontent.com/59051762/222152360-2d0cad68-0536-4b31-bb4d-6835d1a9c7ff.jpg)
