### ISSUE TITLE
Метод containsGame в классе GameStore всегда возвращает false

### ISSUE THREAD

**Issue by Ziplay1997** [Ziplay1997/TeamWork#7]
# Описание
Метод containsGame в классе GameStore всегда возвращает false

# Локация дефекта
https://github.com/Ziplay1997/TeamWork/blob/db8beb77af139750b2acf8a30e3fef6c9446f1f5/src/main/java/ru/netology/GameStore.java#L32-L39

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/Ziplay1997/TeamWork/blob/main/src/test/java/ru/netology/GameStoreTest.java#L8-L15) в IDEA.
2. Запустить тест shouldAddGame
3. Посмотреть на ответ в консоли

**Ожидаемый результат:** Тест проходит. Результат теста true
**Фактический результат:** Тест не проходит. Результат теста false. Сообщение в консоли о несоответствии ожидаемого результата фактическому

# Скриншот
![Снимок экрана 2023-02-28 173759](https://user-images.githubusercontent.com/59051762/221856213-9c92bf5d-e7c8-4a96-91ef-4b21c75668ac.jpg)

# Окружение
Операционная система: Windows 11 Pro
IDE: IntelliJ IDEA Community Edition 2022.2.2
JAVA: Coretto 11.0.17

**Comment by VladislavChu** [comment]
# Код исправлен
![photo_2023-03-01_13-58-04](https://user-images.githubusercontent.com/117576235/222121383-ee93914c-a567-4b08-adb3-9cf0b581ae99.jpg)
