### ISSUE TITLE
Метод getMostPlayer, в классе Gamestore, не принимает значение времени равное 1

### ISSUE THREAD

**Issue by Ziplay1997** [Ziplay1997/TeamWork#8]
# Описание
В классе Gamestore метод getMostPlayer, не принимает значение времени равное 1

# Локация дефекта
https://github.com/Ziplay1997/TeamWork/blob/db8beb77af139750b2acf8a30e3fef6c9446f1f5/src/main/java/ru/netology/GameStore.java#L58-L69

# Шаги воспроизведения
1. Открыть [код программы]() в IDEA.
2. Запустить тест shouldGetMostPlayerEquallyOne
3. Посмотреть на ответ в консоли

**Ожидаемый результат:** Тест проходит. Результат теста - метод getMostPlayer вернул значение имени игрока "Виктор", время добавилось
**Фактический результат:** Тест не проходит. Результат теста false. Сообщение в консоли о несоответствии ожидаемого результата фактическому

# Скриншот
![Снимок экрана 2](https://user-images.githubusercontent.com/59051762/221857067-3710193f-0581-48c8-b917-853885417a68.jpg)

# Окружение
Операционная система: Windows 11 Pro
IDE: IntelliJ IDEA Community Edition 2022.2.2
JAVA: Coretto 11.0.17

**Comment by VladislavChu** [comment]
# Код исправлен
![2](https://user-images.githubusercontent.com/117576235/222122575-fb573cb9-301b-499a-85ac-795e1085c5c2.jpg)
