### ISSUE TITLE
Метод getSumPlayedTime в классе GameStore не возвращает сумму времени всех игроков

### ISSUE THREAD

**Issue by Ziplay1997** [Ziplay1997/TeamWork#9]
# Описание
Метод getSumPlayedTime в классе GameStore не возвращает сумму времени всех игроков, а возвращает ноль

# Локация дефекта
https://github.com/Ziplay1997/TeamWork/blob/db8beb77af139750b2acf8a30e3fef6c9446f1f5/src/main/java/ru/netology/GameStore.java#L75-L77

# Шаги воспроизведения
1. Открыть [код программы]() в IDEA.
2. Запустить тест shouldGetMostPlayerEquallyOne
3. Посмотреть на ответ в консоли

**Ожидаемый результат:** Тест проходит. Время суммируется, метод getSumPlayedTime вернул значение - "7"
**Фактический результат:** Тест не проходит.  Сообщение в консоли о несоответствии ожидаемого результата фактическому

# Скриншот
![Снимок экрана 3](https://user-images.githubusercontent.com/59051762/221857336-ca069fff-75db-4134-b268-5da5e3b4e7a4.jpg)

# Окружение
Операционная система: Windows 11 Pro
IDE: IntelliJ IDEA Community Edition 2022.2.2
JAVA: Coretto 11.0.17

**Comment by VladislavChu** [comment]
# Код исправлен 
![3](https://user-images.githubusercontent.com/117576235/222125418-2c2697e9-23a4-492d-80df-af315d239bdc.jpg)
